version: '3.8'

services:
  # Flask application service
  server-web:
    build: 'flaskr'
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://server-redis:6379  # Set REDIS_URL for Flask app
    networks:
      - webnet  # Red para conectar otros servicios (opcional)

  # Redis service
  server-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - webnet  # Red para conectar otros servicios (opcional)
  # Celery worker service
  worker:
    build: 'flaskr'
    command: celery -A modelos.tareas worker --pool=solo -l info
    volumes:
      - .:/code  # Mount your project directory for worker access
    depends_on:
      - server-web  # Worker depends on the app service being up first
    environment:
      - REDIS_URL=redis://server-redis:6379  # Set REDIS_URL for Celery worker
    networks:
      - webnet
  # Celery worker service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Exponiendo el puerto 80 para Nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Monta tu archivo nginx.conf
    depends_on:
      - server-web  # Nginx depende del servicio de la aplicación
    networks:
      - webnet

networks:
  webnet:
  