version: '3.8'
services:
  # Flask application service
  server-web:
    build: 'flaskr'
    ports:
      - "5000:5000"
    environment:
      - URL_REDIS server-redis
      - DB_USER admin
      - DB_PASSWORD v1d304pp
      - DB_NAME dbvideoapp
      - DB_CONNECTION_NAME 34.123.41.208
    networks:
      - webnet
  # Redis service
  server-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - webnet
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server-web
    networks:
      - webnet
networks:
  webnet: