# Usa la imagen oficial de Nginx como base
FROM nginx:latest

# Copia tus archivos de configuración y contenido estático al contenedor
COPY conf /etc/nginx/conf.d/default.conf


# Exponer el puerto 80
EXPOSE 80

